steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - API_URL=${_API_URL}
      - --build-arg
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_MAPS_BROWSER_API_KEY}
      - --build-arg
      - NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=${_MAPS_MAP_ID}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
